ci: fix docker ecr registery image

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,6 +1,7 @@
 image: maven:3.9.6-eclipse-temurin-21
 
 stages:
+  - .pre
   - build
   - test
   - quality
@@ -14,11 +15,39 @@ variables:
   GIT_DEPTH: "0"
   IMAGE_NAME: "marketplace/catalogue-service"
   IMAGE_TAG: "${CI_COMMIT_SHORT_SHA}"
+  CI_TOOLS_IMAGE: "$CI_REGISTRY_IMAGE/ci-tools:v1.0"
 
 cache:
   paths:
     - .m2/repository
     - .sonar/cache
+
+# ===== PREPARE: Build the CI tools image used by later stages =====
+build-ci-tools:
+  stage: .pre
+  image: docker:27
+  services:
+    - docker:27-dind
+  variables:
+    DOCKER_HOST: "tcp://docker:2376"
+    DOCKER_TLS_CERTDIR: "/certs"
+    DOCKER_CERT_PATH: "/certs/client"
+    DOCKER_TLS_VERIFY: "1"
+  before_script:
+    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
+  script:
+    - |
+      if ! docker pull $CI_TOOLS_IMAGE; then
+        echo "Image $CI_TOOLS_IMAGE not found, building..."
+        docker build -t $CI_TOOLS_IMAGE -f Dockerfile.ci .
+        docker push $CI_TOOLS_IMAGE
+      else
+        echo "Image $CI_TOOLS_IMAGE already exists."
+      fi
+  rules:
+    - changes:
+        - Dockerfile.ci
+    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
 
 # ===== BUILD =====
 build-job:
@@ -56,7 +85,7 @@ package-jar:
 # ===== PUBLISH: build Docker image + push to ECR =====
 publish-image:
   stage: publish
-  image: registry.gitlab.com/abdlatif-nabgha/yanashop/ci-tools:v1.0
+  image: $CI_TOOLS_IMAGE
   services:
     - docker:27-dind
   variables:
@@ -81,7 +110,7 @@ publish-image:
 # ===== DEPLOY TO EKS =====
 deploy-eks:
   stage: deploy
-  image: registry.gitlab.com/abdlatif-nabgha/yanashop/ci-tools:v1.0
+  image: $CI_TOOLS_IMAGE
   before_script:
     - aws eks update-kubeconfig --region $AWS_REGION --name yanashop-eks
   script:
